### ISSUE TITLE
Upgrade to python Docker base using Alpine 3.17 once it's available 

### ISSUE THREAD

**Issue by DBendit** [borgmatic-collective/docker-borgmatic#180]
I'm trying to backup a Postgres 15 DB, which isn't currently supported in Alpine 3.16. Alpine 3.17 adds Postgres 15 support, so once that's available in a Python image, this container should be updated to consume it.

The PR for the Python container to add Alpine 3.17 support is here: https://github.com/docker-library/python/pull/774

This is mostly to raise awareness of the update and keep track of it.

**Comment by grantbevis** [comment]
Thank you @DBendit

**Comment by DBendit** [comment]
Created https://github.com/docker-library/official-images/pull/13604 to get 3.17 built into the official images

**Comment by grantbevis** [comment]
Will wait for that PR to be merged and images built then I'll merge https://github.com/borgmatic-collective/docker-borgmatic/pull/182

**Comment by grantbevis** [comment]
@DBendit - This has been built as :latest for now - a tagged version image will be coming soon when the next version of borgmatic releases

**Comment by DBendit** [comment]
Bad news - trying to run results in lots of errors:

```
/ # /usr/local/bin/borgmatic --stats
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/borg/archiver.py", line 38, in <module>
    from . import helpers
  File "/usr/local/lib/python3.10/site-packages/borg/helpers/__init__.py", line 9, in <module>
    from .checks import *  # NOQA
  File "/usr/local/lib/python3.10/site-packages/borg/helpers/checks.py", line 4, in <module>
    from .errors import Error
  File "/usr/local/lib/python3.10/site-packages/borg/helpers/errors.py", line 3, in <module>
    import borg.crypto.low_level
ImportError: Error loading shared library libcrypto.so.1.1: No such file or directory (needed by /usr/local/lib/python3.10/site-packages/borg/crypto/low_level.cpython-310-x86_64-linux-gnu.so)
/etc/borgmatic.d/guardo.yaml: Error getting local Borg version
Command '('borg', '--version')' returned non-zero exit status 2.
/etc/borgmatic.d/guardo.yaml: Error running configuration file
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/borg/archiver.py", line 38, in <module>
    from . import helpers
  File "/usr/local/lib/python3.10/site-packages/borg/helpers/__init__.py", line 9, in <module>
    from .checks import *  # NOQA
  File "/usr/local/lib/python3.10/site-packages/borg/helpers/checks.py", line 4, in <module>
    from .errors import Error
  File "/usr/local/lib/python3.10/site-packages/borg/helpers/errors.py", line 3, in <module>
    import borg.crypto.low_level
ImportError: Error loading shared library libcrypto.so.1.1: No such file or directory (needed by /usr/local/lib/python3.10/site-packages/borg/crypto/low_level.cpython-310-x86_64-linux-gnu.so)
/etc/borgmatic.d/rsync.yaml: Error getting local Borg version
Command '('borg', '--version')' returned non-zero exit status 2.
/etc/borgmatic.d/rsync.yaml: Error running configuration file

summary:
/etc/borgmatic.d/guardo.yaml: Remote repository paths without ssh:// syntax are deprecated. Interpreting "borg@guardo-tengig.ibendit:/volume2/Backups/borg" as "ssh://borg@guardo-tengig.ibendit/volume2/Backups/borg"
/etc/borgmatic.d/rsync.yaml: Remote repository paths without ssh:// syntax are deprecated. Interpreting "7882@usw-s007.rsync.net:borg" as "ssh://7882@usw-s007.rsync.net/./borg"
/etc/borgmatic.d/guardo.yaml: Error running configuration file
/etc/borgmatic.d/guardo.yaml: Error getting local Borg version
Command '('borg', '--version')' returned non-zero exit status 2.
/etc/borgmatic.d/rsync.yaml: Error running configuration file
/etc/borgmatic.d/rsync.yaml: Error getting local Borg version
Command '('borg', '--version')' returned non-zero exit status 2.

Need some help? https://torsion.org/borgmatic/#issues
```

**Comment by DBendit** [comment]
Oh, yup, looks like this was also reported in https://github.com/borgmatic-collective/docker-borgmatic/issues/184

Apparently Alpine 3.17 switches from OpenSSL 1.1.1 to 3.0.7.
