### ISSUE TITLE
Latest image fails to run borg due to missing libcrypto.so.1.1

### ISSUE THREAD

**Issue by hugalafutro** [borgmatic-collective/docker-borgmatic#184]
Hi,
the latest image from 13h ago fails to run with following error:
```
borgmatic_vm-docker  | borgmatic 1.7.5
borgmatic_vm-docker  |
borgmatic_vm-docker  | apprise 1.2.0
borgmatic_vm-docker  | crond: crond (busybox 1.35.0) started, log level 8
borgmatic_vm-docker  | crond: USER root pid  14 cmd PATH=$PATH:/usr/local/bin /usr/local/bin/borgmatic --stats -v 0 2>&1
borgmatic_vm-docker  | Traceback (most recent call last):
borgmatic_vm-docker  |   File "/usr/local/lib/python3.10/site-packages/borg/archiver.py", line 38, in <module>
borgmatic_vm-docker  |     from . import helpers
borgmatic_vm-docker  |   File "/usr/local/lib/python3.10/site-packages/borg/helpers/__init__.py", line 9, in <module>
borgmatic_vm-docker  |     from .checks import *  # NOQA
borgmatic_vm-docker  |   File "/usr/local/lib/python3.10/site-packages/borg/helpers/checks.py", line 4, in <module>
borgmatic_vm-docker  |     from .errors import Error
borgmatic_vm-docker  |   File "/usr/local/lib/python3.10/site-packages/borg/helpers/errors.py", line 3, in <module>
borgmatic_vm-docker  |     import borg.crypto.low_level
borgmatic_vm-docker  | ImportError: Error loading shared library libcrypto.so.1.1: No such file or directory (needed by /usr/local/lib/python3.10/site-packages/borg/crypto/low_level.cpython-310-x86_64-linux-gnu.so)
borgmatic_vm-docker  | /etc/borgmatic.d/config.yaml: Error getting local Borg version
borgmatic_vm-docker  | Command '('borg', '--version')' returned non-zero exit status 2.
borgmatic_vm-docker  | /etc/borgmatic.d/config.yaml: Error running configuration file
borgmatic_vm-docker  |
borgmatic_vm-docker  | summary:
borgmatic_vm-docker  | /etc/borgmatic.d/config.yaml: Error running configuration file
borgmatic_vm-docker  | /etc/borgmatic.d/config.yaml: Error getting local Borg version
borgmatic_vm-docker  | Command '('borg', '--version')' returned non-zero exit status 2.
borgmatic_vm-docker  |
```
tested on ubuntu vm, rpi3 and rpi4 with same result.

**Comment by hugalafutro** [comment]
as a workaround you can run `apk add libcrypto1.1` inside the container to fix

**Comment by grantbevis** [comment]
The patch provided by @DBendit has just been merged. a new :latest image will be available shortly. Thanks @DBendit
