### ISSUE TITLE
Drop or replace ntfy image as it is/will be broken

### ISSUE THREAD

**Issue by kaechele** [borgmatic-collective/docker-borgmatic#194]
ntfy seems to be largely unmaintained (https://github.com/dschep/ntfy/issues/248) with some sporadic commits but no updates happening to support newer versions of Python or dropping/replacing of unmaintained dependencies (eg. [sleekxmpp](https://github.com/fritzy/SleekXMPP)). Pull Requests are also only sporadically processed.

The `sleekxmpp` dependency is currently also leading to a build error with newer python releases, which leaves ntfy inoperable in current Docker images:
```
[...]
Collecting sleekxmpp
  Downloading sleekxmpp-1.3.3.tar.gz (845 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 845.0/845.0 kB 12.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-arcqy0_c/sleekxmpp_8c99246bf2284a698a8ec6d5f14387e4/setup.py", line 19, in <module>
          from sleekxmpp.version import __version__
        File "/tmp/pip-install-arcqy0_c/sleekxmpp_8c99246bf2284a698a8ec6d5f14387e4/sleekxmpp/__init__.py", line 20, in <module>
          from sleekxmpp.stanza import Message, Presence, Iq
        File "/tmp/pip-install-arcqy0_c/sleekxmpp_8c99246bf2284a698a8ec6d5f14387e4/sleekxmpp/stanza/__init__.py", line 10, in <module>
          from sleekxmpp.stanza.error import Error
        File "/tmp/pip-install-arcqy0_c/sleekxmpp_8c99246bf2284a698a8ec6d5f14387e4/sleekxmpp/stanza/error.py", line 9, in <module>
          from sleekxmpp.xmlstream import ElementBase, ET
        File "/tmp/pip-install-arcqy0_c/sleekxmpp_8c99246bf2284a698a8ec6d5f14387e4/sleekxmpp/xmlstream/__init__.py", line 9, in <module>
          from sleekxmpp.jid import JID
        File "/tmp/pip-install-arcqy0_c/sleekxmpp_8c99246bf2284a698a8ec6d5f14387e4/sleekxmpp/jid.py", line 25, in <module>
          from sleekxmpp.thirdparty import OrderedDict
        File "/tmp/pip-install-arcqy0_c/sleekxmpp_8c99246bf2284a698a8ec6d5f14387e4/sleekxmpp/thirdparty/__init__.py", line 13, in <module>
          from sleekxmpp.thirdparty.orderedset import OrderedSet
        File "/tmp/pip-install-arcqy0_c/sleekxmpp_8c99246bf2284a698a8ec6d5f14387e4/sleekxmpp/thirdparty/orderedset.py", line 25, in <module>
          class OrderedSet(collections.MutableSet):
                           ^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'collections' has no attribute 'MutableSet'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
[...]
```

So this will need some attention sooner or later.

In my cursory searches I haven't found a 1:1 replacement option but [ntfy.sh](https://ntfy.sh/) could be an option, albeit not as comfortable as just sending notifications to external services and messengers using the current ntfy.

The other alternative is to fork ntfy / find a maintained fork of it. I might look into this if there is enough interest.

**Comment by kaechele** [comment]
https://github.com/borgmatic-collective/docker-borgmatic/issues/144#issuecomment-1354018010 addresses this.
