### ISSUE TITLE
Need help with configuration error (deep merging)

### ISSUE THREAD

**Issue by rallisf1** [borgmatic-collective/docker-borgmatic#232]
I'm trying to use deep merging to backup multiple websites in a single repository using a common config plus one config per website.

Host: Almalinux 8.7 x86_64
Docker: 23.0.6, build ef23cbc
Docker Compose: 2.17.3
borgmatic 1.7.12
borg 1.2.4
apprise 1.3.0

### Error ###
```shell
c7c27a7e3c24:/etc/borgmatic.d# validate-borgmatic-config --show
Traceback (most recent call last):
  File "/usr/local/bin/validate-borgmatic-config", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/borgmatic/commands/validate_config.py", line 50, in main
    config, parse_logs = validate.parse_configuration(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/borgmatic/config/validate.py", line 101, in parse_configuration
    config = load.load_configuration(config_filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/borgmatic/config/load.py", line 138, in load_configuration
    config = yaml.load(file_contents)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ruamel/yaml/main.py", line 426, in load
    return constructor.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 113, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 122, in construct_document
    for _dummy in generator:
  File "/usr/local/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 612, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ruamel/yaml/constructor.py", line 409, in construct_mapping
    self.flatten_mapping(node)
  File "/usr/local/lib/python3.11/site-packages/borgmatic/config/load.py", line 112, in flatten_mapping
    node.value = deep_merge_nodes(node.value)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/borgmatic/config/load.py", line 255, in deep_merge_nodes
    value=deep_merge_nodes(a_value.value + b_value.value),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/borgmatic/config/load.py", line 274, in deep_merge_nodes
    value=filter_omitted_nodes(a_value.value + b_value.value),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/borgmatic/config/load.py", line 156, in filter_omitted_nodes
    omitted_values = tuple(node.value for node in nodes if node.tag == '!omit')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/borgmatic/config/load.py", line 156, in <genexpr>
    omitted_values = tuple(node.value for node in nodes if node.tag == '!omit')
                                                           ^^^^^^^^
AttributeError: 'tuple' object has no attribute 'tag'
```

### common.yaml ###
```yaml
location:
  repositories:
    - path: ssh://my.sftp.server/home/backup
      label: backup.server
  source_directories:
  exclude_patterns:
    - '*/cache/*'
    - '*/tmp/*'
    - '*/temp/*'

retention:
  keep_daily: 7
  keep_weekly: 4
  keep_monthly: 2
  prefix: ""

consistency:
  checks:
    - name: repository
    - name: archives
      frequency: 2 weeks

hooks:
  mysql_databases:
      username: root
      password: mydbpass
  healthchecks:
    states:
      - finish
      - fail
```

### domain.yaml ###
```yaml
<<: !include /etc/borgmatic.d/common.yaml

location:
  source_directories:
    - /mnt/source/home/mydomain.com
    - /mnt/source/usr/local/lsws/conf/vhosts/mydomain.com
    - /mnt/source/etc/letsencrypt/live/mydomain.com

hooks:
  mysql_databases:
    - name: mydomain_db
  healthchecks:
    ping_url: https://my.webhook.endpoint/mydomain.com
```

### system.yaml ###
```yaml
<<: !include /etc/borgmatic.d/common.yaml

location:
  source_directories:
    - /mnt/source/home/docker
    - /mnt/source/usr/local/lsws/conf/*.*
    - /mnt/source/usr/local/lsws/lsphp*/etc/php.ini
    - /mnt/source/etc/csf/csf.*
    - /mnt/source/etc/my.cnf

hooks:
  mysql_databases:
    - name: mycpdb
   healthchecks:
    ping_url: https://my.webhook.endpoint/system
```

P.S. This is brand new setup, I haven't even initialized the repo yet. Will do so as soon as the config validates.

**Comment by witten** [comment]
And FYI I see two problems with your `common.yaml`, one of which I think it causing this:

 * The `mysql_databases:` value needs to be a list of database objects. Right now it just has a bare `username` and `password`.
 * `source_directories:` is empty/null. It should be a list. If you want it to be an empty list, do this: `[]`.

**Comment by rallisf1** [comment]
> And FYI I see two problems with your `common.yaml`, one of which I think it causing this:
> 
> * The `mysql_databases:` value needs to be a list of database objects. Right now it just has a bare `username` and `password`.
> * `source_directories:` is empty/null. It should be a list. If you want it to be an empty list, do this: `[]`.

Good catch, I'll test it out tomorrow, hopefully this is it.

**Comment by rallisf1** [comment]
I fixed the configuration and now it works. thanks!

P.S. It would be great if borgmatic had proper error handling, like tell me what's wrong with my config. It would make issues like this obsolete.

**Comment by witten** [comment]
Glad to hear it work! Agreed about error messages. In the future, please file borgmatic-specific (e.g. not container-specific) issues here for prompt attention: https://torsion.org/borgmatic/#issues

**Comment by witten** [comment]
Okay, I've just pushed some changes, and the next version of borgmatic should produce a much nicer error message when the situation from this ticket occurs.
