### ISSUE TITLE
BORG_RSH does not work

### ISSUE THREAD

**Issue by dave12311** [borgmatic-collective/docker-borgmatic#260]
Command specified by `BORG_RSH` does not seem to get passed to ssh.

E.g. trying to specify a key with a non-default name `BORG_RSH="ssh -i /root/.ssh/borgbase"` results in
```
SSH command line: ['ssh', '<REDACTED>.repo.borgbase.com', 'borg', 'serve', '--debug']
Remote: <REDACTED>.repo.borgbase.com: Permission denied (publickey).
Connection closed by remote host. Is borg working on the server?
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/borg/archiver.py", line 5324, in main
    exit_code = archiver.run(args)
                ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/borg/archiver.py", line 5255, in run
    return set_ec(func(args))
                  ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/borg/archiver.py", line 161, in wrapper
    repository = RemoteRepository(location.omit_archive(), create=create, exclusive=argument(args, exclusive),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/borg/remote.py", line 578, in __init__
    raise ConnectionClosedWithHint('Is borg working on the server?') from None
borg.remote.ConnectionClosedWithHint: Connection closed by remote host. Is borg working on the server?

Platform: Linux 198e743aacb9 5.10.160-rk35xx #1 SMP Thu Jul 6 13:36:29 UTC 2023 aarch64
Linux: Unknown Linux  
Borg: 1.2.6  Python: CPython 3.11.5 msgpack: 1.0.5 fuse: llfuse 1.5.0 [pyfuse3,llfuse]
PID: 15  CWD: /
sys.argv: ['/usr/local/bin/borg', 'init', '--encryption', 'repokey-blake2', '--debug', 'ssh://<REDACTED>.repo.borgbase.com/./repo']
SSH_ORIGINAL_COMMAND: None
```

Renaming the key to the default `id_rsa` works.

**Comment by witten** [comment]
You may already be aware, but you can set the `ssh_command` option in borgmatic's configuration instead of the `BORG_SSH` environment variable.

**Comment by modem7** [comment]
@dave12311 - did @witten's comment assist? Are you still having this issue?

**Comment by dave12311** [comment]
I ended up just passing the key with the default name using `VOLUME_SSH`, but I guess the documentation should still be updated to reflect this. Thanks for the help though!

**Comment by modem7** [comment]
> I ended up just passing the key with the default name using `VOLUME_SSH`, but I guess the documentation should still be updated to reflect this. Thanks for the help though!

Happy to review a PR for this!

**Comment by modem7** [comment]
This is an S6 environment variable scoping issue from the time — `BORG_RSH` set via `environment:` in compose was available in the container but not being picked up by borgmatic when run via cron, as cron jobs didn't inherit the full S6 environment.

This is resolved in #487 — all environment variables including `BORG_RSH` are correctly passed through to borgmatic.

That said, the recommended approach for SSH key configuration is to set it in your borgmatic config rather than relying on the environment variable, as it's more explicit and portable:

```yaml
ssh_command: ssh -i /root/.ssh/borgbase
```

This goes at the top level of your borgmatic config and applies to all repositories.
